apiVersion: cluster.incus.crossplane.io/v1alpha1
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: cluster/v1alpha1/certificate
  labels:
    testing.upbound.io/example-name: client1
  name: client1
spec:
  forProvider:
    certificate: ${file("${path.module}/metrics.crt")}
