apiVersion: storage.incus.m.crossplane.io/v1alpha1
kind: Volume
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: volume1
  name: volume1
  namespace: crossplane-system
spec:
  forProvider:
    poolSelector:
      matchLabels:
        testing.upbound.io/example-name: pool1

---

apiVersion: storage.incus.m.crossplane.io/v1alpha1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: pool1
  name: pool1
  namespace: crossplane-system
spec:
  forProvider:
    driver: zfs
    name: mypool
