// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AliasInitParameters struct {

	// Optional - A description for the alias.
	// The description for the image alias.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - The name of the alias.
	// The name of the image alias.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AliasObservation struct {

	// Optional - A description for the alias.
	// The description for the image alias.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - The name of the alias.
	// The name of the image alias.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AliasParameters struct {

	// Optional - A description for the alias.
	// The description for the image alias.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - The name of the alias.
	// The name of the image alias.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type ImageInitParameters struct {

	// Image alias
	Alias []AliasInitParameters `json:"alias,omitempty" tf:"alias,omitempty"`

	// Optional - Name of the project where the image will be stored.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - The image file from the local file system from which the image will be created. See reference below.
	SourceFile *SourceFileInitParameters `json:"sourceFile,omitempty" tf:"source_file,omitempty"`

	// Optional - The source image from which the image will be created. See reference below.
	SourceImage *SourceImageInitParameters `json:"sourceImage,omitempty" tf:"source_image,omitempty"`

	// Optional - The source instance from which the image will be created. See reference below.
	SourceInstance *SourceInstanceInitParameters `json:"sourceInstance,omitempty" tf:"source_instance,omitempty"`
}

type ImageObservation struct {

	// Image alias
	Alias []AliasObservation `json:"alias,omitempty" tf:"alias,omitempty"`

	// The list of aliases that were copied from the
	// source_image.
	// +listType=set
	CopiedAliases []*string `json:"copiedAliases,omitempty" tf:"copied_aliases,omitempty"`

	// The datetime of image creation, in Unix time.
	CreatedAt *float64 `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// The unique hash fingerprint of the image.
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Optional - Name of the project where the image will be stored.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// Optional - The image file from the local file system from which the image will be created. See reference below.
	SourceFile *SourceFileObservation `json:"sourceFile,omitempty" tf:"source_file,omitempty"`

	// Optional - The source image from which the image will be created. See reference below.
	SourceImage *SourceImageObservation `json:"sourceImage,omitempty" tf:"source_image,omitempty"`

	// Optional - The source instance from which the image will be created. See reference below.
	SourceInstance *SourceInstanceObservation `json:"sourceInstance,omitempty" tf:"source_instance,omitempty"`
}

type ImageParameters struct {

	// Image alias
	// +kubebuilder:validation:Optional
	Alias []AliasParameters `json:"alias,omitempty" tf:"alias,omitempty"`

	// Optional - Name of the project where the image will be stored.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	// +kubebuilder:validation:Optional
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - The image file from the local file system from which the image will be created. See reference below.
	// +kubebuilder:validation:Optional
	SourceFile *SourceFileParameters `json:"sourceFile,omitempty" tf:"source_file,omitempty"`

	// Optional - The source image from which the image will be created. See reference below.
	// +kubebuilder:validation:Optional
	SourceImage *SourceImageParameters `json:"sourceImage,omitempty" tf:"source_image,omitempty"`

	// Optional - The source instance from which the image will be created. See reference below.
	// +kubebuilder:validation:Optional
	SourceInstance *SourceInstanceParameters `json:"sourceInstance,omitempty" tf:"source_instance,omitempty"`
}

type SourceFileInitParameters struct {

	// Required - Either the path of an unified image
	// or the rootfs tarball of a split image, depending on
	// metadata_path being provided or not.
	DataPath *string `json:"dataPath,omitempty" tf:"data_path,omitempty"`

	// Optional - Path to the metadata tarball of a split image.
	MetadataPath *string `json:"metadataPath,omitempty" tf:"metadata_path,omitempty"`
}

type SourceFileObservation struct {

	// Required - Either the path of an unified image
	// or the rootfs tarball of a split image, depending on
	// metadata_path being provided or not.
	DataPath *string `json:"dataPath,omitempty" tf:"data_path,omitempty"`

	// Optional - Path to the metadata tarball of a split image.
	MetadataPath *string `json:"metadataPath,omitempty" tf:"metadata_path,omitempty"`
}

type SourceFileParameters struct {

	// Required - Either the path of an unified image
	// or the rootfs tarball of a split image, depending on
	// metadata_path being provided or not.
	// +kubebuilder:validation:Optional
	DataPath *string `json:"dataPath" tf:"data_path,omitempty"`

	// Optional - Path to the metadata tarball of a split image.
	// +kubebuilder:validation:Optional
	MetadataPath *string `json:"metadataPath,omitempty" tf:"metadata_path,omitempty"`
}

type SourceImageInitParameters struct {

	// Optional - The image architecture (e.g. x86_64, aarch64). See Architectures for all possible values.
	Architecture *string `json:"architecture,omitempty" tf:"architecture,omitempty"`

	// Optional - Whether to copy the aliases of the image from
	// the remote. Valid values are true and false.
	CopyAliases *bool `json:"copyAliases,omitempty" tf:"copy_aliases,omitempty"`

	// Required - Name of the image.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Required - The remote where the image will be pulled from.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - Type of image to cache. Must be one of container or
	// virtual-machine. Defaults to container.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SourceImageObservation struct {

	// Optional - The image architecture (e.g. x86_64, aarch64). See Architectures for all possible values.
	Architecture *string `json:"architecture,omitempty" tf:"architecture,omitempty"`

	// Optional - Whether to copy the aliases of the image from
	// the remote. Valid values are true and false.
	CopyAliases *bool `json:"copyAliases,omitempty" tf:"copy_aliases,omitempty"`

	// Required - Name of the image.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Required - The remote where the image will be pulled from.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - Type of image to cache. Must be one of container or
	// virtual-machine. Defaults to container.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SourceImageParameters struct {

	// Optional - The image architecture (e.g. x86_64, aarch64). See Architectures for all possible values.
	// +kubebuilder:validation:Optional
	Architecture *string `json:"architecture,omitempty" tf:"architecture,omitempty"`

	// Optional - Whether to copy the aliases of the image from
	// the remote. Valid values are true and false.
	// +kubebuilder:validation:Optional
	CopyAliases *bool `json:"copyAliases,omitempty" tf:"copy_aliases,omitempty"`

	// Required - Name of the image.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Required - The remote where the image will be pulled from.
	// +kubebuilder:validation:Optional
	Remote *string `json:"remote" tf:"remote,omitempty"`

	// Optional - Type of image to cache. Must be one of container or
	// virtual-machine. Defaults to container.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SourceInstanceInitParameters struct {

	// Required - Name of the source instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Optional - Name of the snapshot of the source instance
	Snapshot *string `json:"snapshot,omitempty" tf:"snapshot,omitempty"`
}

type SourceInstanceObservation struct {

	// Required - Name of the source instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Optional - Name of the snapshot of the source instance
	Snapshot *string `json:"snapshot,omitempty" tf:"snapshot,omitempty"`
}

type SourceInstanceParameters struct {

	// Required - Name of the source instance.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Optional - Name of the snapshot of the source instance
	// +kubebuilder:validation:Optional
	Snapshot *string `json:"snapshot,omitempty" tf:"snapshot,omitempty"`
}

// ImageSpec defines the desired state of Image
type ImageSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ImageParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ImageInitParameters `json:"initProvider,omitempty"`
}

// ImageStatus defines the observed state of Image.
type ImageStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ImageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Image is the Schema for the Images API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,incus}
type Image struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ImageSpec   `json:"spec"`
	Status            ImageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ImageList contains a list of Images
type ImageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Image `json:"items"`
}

// Repository type metadata.
var (
	Image_Kind             = "Image"
	Image_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Image_Kind}.String()
	Image_KindAPIVersion   = Image_Kind + "." + CRDGroupVersion.String()
	Image_GroupVersionKind = CRDGroupVersion.WithKind(Image_Kind)
)

func init() {
	SchemeBuilder.Register(&Image{}, &ImageList{})
}
