// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CertificateInitParameters struct {

	// Required - The certificate.
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// Optional - Description of the certificate.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Optional -  List of projects to restrict the certificate to.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/cluster/project/v1alpha1.Project
	// +listType=set
	Projects []*string `json:"projects,omitempty" tf:"projects,omitempty"`

	// References to Project in project to populate projects.
	// +kubebuilder:validation:Optional
	ProjectsRefs []v2.Reference `json:"projectsRefs,omitempty" tf:"-"`

	// Selector for a list of Project in project to populate projects.
	// +kubebuilder:validation:Optional
	ProjectsSelector *v2.Selector `json:"projectsSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional -  Restrict the certificate to one or more projects.
	Restricted *bool `json:"restricted,omitempty" tf:"restricted,omitempty"`

	// Optional - The type of certificate to create. Can be one of: client,
	// or metrics. If no type is specified, a client certificate is created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type CertificateObservation struct {

	// Required - The certificate.
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// Optional - Description of the certificate.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The fingerprint of the certificate.
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Optional -  List of projects to restrict the certificate to.
	// +listType=set
	Projects []*string `json:"projects,omitempty" tf:"projects,omitempty"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional -  Restrict the certificate to one or more projects.
	Restricted *bool `json:"restricted,omitempty" tf:"restricted,omitempty"`

	// Optional - The type of certificate to create. Can be one of: client,
	// or metrics. If no type is specified, a client certificate is created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type CertificateParameters struct {

	// Required - The certificate.
	// +kubebuilder:validation:Optional
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// Optional - Description of the certificate.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Optional -  List of projects to restrict the certificate to.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/cluster/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	// +listType=set
	Projects []*string `json:"projects,omitempty" tf:"projects,omitempty"`

	// References to Project in project to populate projects.
	// +kubebuilder:validation:Optional
	ProjectsRefs []v2.Reference `json:"projectsRefs,omitempty" tf:"-"`

	// Selector for a list of Project in project to populate projects.
	// +kubebuilder:validation:Optional
	ProjectsSelector *v2.Selector `json:"projectsSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	// +kubebuilder:validation:Optional
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional -  Restrict the certificate to one or more projects.
	// +kubebuilder:validation:Optional
	Restricted *bool `json:"restricted,omitempty" tf:"restricted,omitempty"`

	// Optional - The type of certificate to create. Can be one of: client,
	// or metrics. If no type is specified, a client certificate is created.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// CertificateSpec defines the desired state of Certificate
type CertificateSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   CertificateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CertificateInitParameters `json:"initProvider,omitempty"`
}

// CertificateStatus defines the observed state of Certificate.
type CertificateStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CertificateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Certificate is the Schema for the Certificates API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incus}
type Certificate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.certificate) || (has(self.initProvider) && has(self.initProvider.certificate))",message="spec.forProvider.certificate is a required parameter"
	Spec   CertificateSpec   `json:"spec"`
	Status CertificateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CertificateList contains a list of Certificates
type CertificateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Certificate `json:"items"`
}

// Repository type metadata.
var (
	Certificate_Kind             = "Certificate"
	Certificate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Certificate_Kind}.String()
	Certificate_KindAPIVersion   = Certificate_Kind + "." + CRDGroupVersion.String()
	Certificate_GroupVersionKind = CRDGroupVersion.WithKind(Certificate_Kind)
)

func init() {
	SchemeBuilder.Register(&Certificate{}, &CertificateList{})
}
