apiVersion: instance.incus.crossplane.io/v1alpha1
kind: Snapshot
metadata:
  annotations:
    meta.upbound.io/example-id: instance/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: snap1
  name: snap1
spec:
  forProvider:
    instanceSelector:
      matchLabels:
        testing.upbound.io/example-name: instance

---

apiVersion: instance.incus.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: instance/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: instance
  name: instance
spec:
  forProvider:
    ephemeral: false
    imageSelector:
      matchLabels:
        testing.upbound.io/example-name: example
