#!/usr/bin/env python3
"""Renders package/crossplane.yaml from the files in extensions/.

Package registries and the Upbound Marketplace read a provider's readme and
icon from the package metadata annotations, not from extensions/, which
`crossplane xpkg build` doesn't package. Edit extensions/readme/readme.md and
extensions/icons/icon.svg, then run `make generate` (or this script).
"""

import base64
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
README = ROOT / "extensions" / "readme" / "readme.md"
ICON = ROOT / "extensions" / "icons" / "icon.svg"
OUT = ROOT / "package" / "crossplane.yaml"


def block(text: str, indent: int) -> str:
    pad = " " * indent
    return "\n".join(pad + line if line else "" for line in text.rstrip("\n").split("\n"))


def main() -> None:
    readme = README.read_text()
    # Comments are for editors of the SVG, not for the rendered icon.
    icon = re.sub(r"<!--.*?-->", "", ICON.read_text(), flags=re.S)
    icon = re.sub(r">\s+<", "><", icon).strip()
    icon_uri = "data:image/svg+xml;base64," + base64.b64encode(icon.encode()).decode()

    OUT.write_text(f"""# Code generated by hack/package-metadata.py from extensions/. DO NOT EDIT.
apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-incus
  annotations:
    friendly-name.meta.crossplane.io: Provider Incus
    meta.crossplane.io/maintainer: Léo Nonnenmacher (https://github.com/l-nmch)
    meta.crossplane.io/source: github.com/l-nmch/provider-incus
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Crossplane provider for Incus: projects, instances, profiles, images,
      storage, networks and cluster configuration.
    meta.crossplane.io/iconURI: {icon_uri}
    meta.crossplane.io/readme: |
{block(readme, 6)}
spec:
  capabilities:
    - SafeStart
""")


if __name__ == "__main__":
    main()
