// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ForwardInitParameters struct {

	// Optional - Map of key/value pairs of
	// network forward config settings.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network forward.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - IP address to listen on.
	ListenAddress *string `json:"listenAddress,omitempty" tf:"listen_address,omitempty"`

	// Required - Name of the network.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/network/v1alpha1.Network
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Reference to a Network in network to populate network.
	// +kubebuilder:validation:Optional
	NetworkRef *v2.NamespacedReference `json:"networkRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate network.
	// +kubebuilder:validation:Optional
	NetworkSelector *v2.NamespacedSelector `json:"networkSelector,omitempty" tf:"-"`

	// Optional - List of port specifications. See reference below.
	Ports []PortsInitParameters `json:"ports,omitempty" tf:"ports,omitempty"`

	// Optional - Name of the project where the network forward will be created.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`
}

type ForwardObservation struct {

	// Optional - Map of key/value pairs of
	// network forward config settings.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network forward.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Required - IP address to listen on.
	ListenAddress *string `json:"listenAddress,omitempty" tf:"listen_address,omitempty"`

	// Required - Name of the network.
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Optional - List of port specifications. See reference below.
	Ports []PortsObservation `json:"ports,omitempty" tf:"ports,omitempty"`

	// Optional - Name of the project where the network forward will be created.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`
}

type ForwardParameters struct {

	// Optional - Map of key/value pairs of
	// network forward config settings.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network forward.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - IP address to listen on.
	// +kubebuilder:validation:Optional
	ListenAddress *string `json:"listenAddress,omitempty" tf:"listen_address,omitempty"`

	// Required - Name of the network.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/network/v1alpha1.Network
	// +kubebuilder:validation:Optional
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Reference to a Network in network to populate network.
	// +kubebuilder:validation:Optional
	NetworkRef *v2.NamespacedReference `json:"networkRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate network.
	// +kubebuilder:validation:Optional
	NetworkSelector *v2.NamespacedSelector `json:"networkSelector,omitempty" tf:"-"`

	// Optional - List of port specifications. See reference below.
	// +kubebuilder:validation:Optional
	Ports []PortsParameters `json:"ports,omitempty" tf:"ports,omitempty"`

	// Optional - Name of the project where the network forward will be created.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	// +kubebuilder:validation:Optional
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`
}

type PortsInitParameters struct {

	// Optional - Description of the network forward.
	// Port description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - Listen port(s) (e.g. 80,90-100)
	// Listen port to forward
	ListenPort *string `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// Required - Protocol for the port(s) (tcp or udp). If not set then tcp will be used.
	// Port protocol
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Required - IP address to forward to
	// Target address to forward listen port to
	TargetAddress *string `json:"targetAddress,omitempty" tf:"target_address,omitempty"`

	// Optional - T arget port(s) (e.g. 70,80-90 or 90), same as listen_port if empty
	// Target port to forward listen port to
	TargetPort *string `json:"targetPort,omitempty" tf:"target_port,omitempty"`
}

type PortsObservation struct {

	// Optional - Description of the network forward.
	// Port description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - Listen port(s) (e.g. 80,90-100)
	// Listen port to forward
	ListenPort *string `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// Required - Protocol for the port(s) (tcp or udp). If not set then tcp will be used.
	// Port protocol
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Required - IP address to forward to
	// Target address to forward listen port to
	TargetAddress *string `json:"targetAddress,omitempty" tf:"target_address,omitempty"`

	// Optional - T arget port(s) (e.g. 70,80-90 or 90), same as listen_port if empty
	// Target port to forward listen port to
	TargetPort *string `json:"targetPort,omitempty" tf:"target_port,omitempty"`
}

type PortsParameters struct {

	// Optional - Description of the network forward.
	// Port description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - Listen port(s) (e.g. 80,90-100)
	// Listen port to forward
	// +kubebuilder:validation:Optional
	ListenPort *string `json:"listenPort" tf:"listen_port,omitempty"`

	// Required - Protocol for the port(s) (tcp or udp). If not set then tcp will be used.
	// Port protocol
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Required - IP address to forward to
	// Target address to forward listen port to
	// +kubebuilder:validation:Optional
	TargetAddress *string `json:"targetAddress" tf:"target_address,omitempty"`

	// Optional - T arget port(s) (e.g. 70,80-90 or 90), same as listen_port if empty
	// Target port to forward listen port to
	// +kubebuilder:validation:Optional
	TargetPort *string `json:"targetPort" tf:"target_port,omitempty"`
}

// ForwardSpec defines the desired state of Forward
type ForwardSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ForwardParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ForwardInitParameters `json:"initProvider,omitempty"`
}

// ForwardStatus defines the observed state of Forward.
type ForwardStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ForwardObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Forward is the Schema for the Forwards API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,incus}
type Forward struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.listenAddress) || (has(self.initProvider) && has(self.initProvider.listenAddress))",message="spec.forProvider.listenAddress is a required parameter"
	Spec   ForwardSpec   `json:"spec"`
	Status ForwardStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ForwardList contains a list of Forwards
type ForwardList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Forward `json:"items"`
}

// Repository type metadata.
var (
	Forward_Kind             = "Forward"
	Forward_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Forward_Kind}.String()
	Forward_KindAPIVersion   = Forward_Kind + "." + CRDGroupVersion.String()
	Forward_GroupVersionKind = CRDGroupVersion.WithKind(Forward_Kind)
)

func init() {
	SchemeBuilder.Register(&Forward{}, &ForwardList{})
}
