// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type BackendInitParameters struct {

	// LB backend description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// LB backend name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// LB backend target address
	TargetAddress *string `json:"targetAddress,omitempty" tf:"target_address,omitempty"`

	// LB backend target port
	TargetPort *string `json:"targetPort,omitempty" tf:"target_port,omitempty"`
}

type BackendObservation struct {

	// LB backend description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// LB backend name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// LB backend target address
	TargetAddress *string `json:"targetAddress,omitempty" tf:"target_address,omitempty"`

	// LB backend target port
	TargetPort *string `json:"targetPort,omitempty" tf:"target_port,omitempty"`
}

type BackendParameters struct {

	// LB backend description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// LB backend name
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// LB backend target address
	// +kubebuilder:validation:Optional
	TargetAddress *string `json:"targetAddress" tf:"target_address,omitempty"`

	// LB backend target port
	// +kubebuilder:validation:Optional
	TargetPort *string `json:"targetPort,omitempty" tf:"target_port,omitempty"`
}

type LoadBalancerInitParameters struct {

	// Network load balancer backend
	Backend []BackendInitParameters `json:"backend,omitempty" tf:"backend,omitempty"`

	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ListenAddress *string `json:"listenAddress,omitempty" tf:"listen_address,omitempty"`

	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/network/v1alpha1.Network
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Reference to a Network in network to populate network.
	// +kubebuilder:validation:Optional
	NetworkRef *v2.NamespacedReference `json:"networkRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate network.
	// +kubebuilder:validation:Optional
	NetworkSelector *v2.NamespacedSelector `json:"networkSelector,omitempty" tf:"-"`

	// Network load balancer port
	Port []PortInitParameters `json:"port,omitempty" tf:"port,omitempty"`

	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`
}

type LoadBalancerObservation struct {

	// Network load balancer backend
	Backend []BackendObservation `json:"backend,omitempty" tf:"backend,omitempty"`

	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	ListenAddress *string `json:"listenAddress,omitempty" tf:"listen_address,omitempty"`

	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Network load balancer port
	Port []PortObservation `json:"port,omitempty" tf:"port,omitempty"`

	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`
}

type LoadBalancerParameters struct {

	// Network load balancer backend
	// +kubebuilder:validation:Optional
	Backend []BackendParameters `json:"backend,omitempty" tf:"backend,omitempty"`

	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	ListenAddress *string `json:"listenAddress,omitempty" tf:"listen_address,omitempty"`

	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/network/v1alpha1.Network
	// +kubebuilder:validation:Optional
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Reference to a Network in network to populate network.
	// +kubebuilder:validation:Optional
	NetworkRef *v2.NamespacedReference `json:"networkRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate network.
	// +kubebuilder:validation:Optional
	NetworkSelector *v2.NamespacedSelector `json:"networkSelector,omitempty" tf:"-"`

	// Network load balancer port
	// +kubebuilder:validation:Optional
	Port []PortParameters `json:"port,omitempty" tf:"port,omitempty"`

	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`
}

type PortInitParameters struct {

	// Port description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Port to listen to
	ListenPort *string `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// Port protocol
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// List of target LB backends
	// +listType=set
	TargetBackend []*string `json:"targetBackend,omitempty" tf:"target_backend,omitempty"`
}

type PortObservation struct {

	// Port description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Port to listen to
	ListenPort *string `json:"listenPort,omitempty" tf:"listen_port,omitempty"`

	// Port protocol
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// List of target LB backends
	// +listType=set
	TargetBackend []*string `json:"targetBackend,omitempty" tf:"target_backend,omitempty"`
}

type PortParameters struct {

	// Port description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Port to listen to
	// +kubebuilder:validation:Optional
	ListenPort *string `json:"listenPort" tf:"listen_port,omitempty"`

	// Port protocol
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// List of target LB backends
	// +kubebuilder:validation:Optional
	// +listType=set
	TargetBackend []*string `json:"targetBackend" tf:"target_backend,omitempty"`
}

// LoadBalancerSpec defines the desired state of LoadBalancer
type LoadBalancerSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            LoadBalancerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoadBalancerInitParameters `json:"initProvider,omitempty"`
}

// LoadBalancerStatus defines the observed state of LoadBalancer.
type LoadBalancerStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               LoadBalancerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LoadBalancer is the Schema for the LoadBalancers API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,incus}
type LoadBalancer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.listenAddress) || (has(self.initProvider) && has(self.initProvider.listenAddress))",message="spec.forProvider.listenAddress is a required parameter"
	Spec   LoadBalancerSpec   `json:"spec"`
	Status LoadBalancerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoadBalancerList contains a list of LoadBalancers
type LoadBalancerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoadBalancer `json:"items"`
}

// Repository type metadata.
var (
	LoadBalancer_Kind             = "LoadBalancer"
	LoadBalancer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LoadBalancer_Kind}.String()
	LoadBalancer_KindAPIVersion   = LoadBalancer_Kind + "." + CRDGroupVersion.String()
	LoadBalancer_GroupVersionKind = CRDGroupVersion.WithKind(LoadBalancer_Kind)
)

func init() {
	SchemeBuilder.Register(&LoadBalancer{}, &LoadBalancerList{})
}
