// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PeerInitParameters struct {

	// Optional - Configuration options as key/value pairs (only user.* custom keys supported)
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network peering
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - Name of the local network.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/network/v1alpha1.Network
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Reference to a Network in network to populate network.
	// +kubebuilder:validation:Optional
	NetworkRef *v2.NamespacedReference `json:"networkRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate network.
	// +kubebuilder:validation:Optional
	NetworkSelector *v2.NamespacedSelector `json:"networkSelector,omitempty" tf:"-"`

	// Optional - Name of the project where the network is located.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/network/v1alpha1.Integration
	TargetIntegration *string `json:"targetIntegration,omitempty" tf:"target_integration,omitempty"`

	// Reference to a Integration in network to populate targetIntegration.
	// +kubebuilder:validation:Optional
	TargetIntegrationRef *v2.NamespacedReference `json:"targetIntegrationRef,omitempty" tf:"-"`

	// Selector for a Integration in network to populate targetIntegration.
	// +kubebuilder:validation:Optional
	TargetIntegrationSelector *v2.NamespacedSelector `json:"targetIntegrationSelector,omitempty" tf:"-"`

	// required - Which network to create a peering with
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/network/v1alpha1.Network
	TargetNetwork *string `json:"targetNetwork,omitempty" tf:"target_network,omitempty"`

	// Reference to a Network in network to populate targetNetwork.
	// +kubebuilder:validation:Optional
	TargetNetworkRef *v2.NamespacedReference `json:"targetNetworkRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate targetNetwork.
	// +kubebuilder:validation:Optional
	TargetNetworkSelector *v2.NamespacedSelector `json:"targetNetworkSelector,omitempty" tf:"-"`

	// Optional - Which project the target network exists in
	TargetProject *string `json:"targetProject,omitempty" tf:"target_project,omitempty"`

	// Optional - Type of network peering
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type PeerObservation struct {

	// Optional - Configuration options as key/value pairs (only user.* custom keys supported)
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network peering
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Required - Name of the local network.
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Optional - Name of the project where the network is located.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	TargetIntegration *string `json:"targetIntegration,omitempty" tf:"target_integration,omitempty"`

	// required - Which network to create a peering with
	TargetNetwork *string `json:"targetNetwork,omitempty" tf:"target_network,omitempty"`

	// Optional - Which project the target network exists in
	TargetProject *string `json:"targetProject,omitempty" tf:"target_project,omitempty"`

	// Optional - Type of network peering
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type PeerParameters struct {

	// Optional - Configuration options as key/value pairs (only user.* custom keys supported)
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network peering
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - Name of the local network.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/network/v1alpha1.Network
	// +kubebuilder:validation:Optional
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Reference to a Network in network to populate network.
	// +kubebuilder:validation:Optional
	NetworkRef *v2.NamespacedReference `json:"networkRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate network.
	// +kubebuilder:validation:Optional
	NetworkSelector *v2.NamespacedSelector `json:"networkSelector,omitempty" tf:"-"`

	// Optional - Name of the project where the network is located.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	// +kubebuilder:validation:Optional
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/network/v1alpha1.Integration
	// +kubebuilder:validation:Optional
	TargetIntegration *string `json:"targetIntegration,omitempty" tf:"target_integration,omitempty"`

	// Reference to a Integration in network to populate targetIntegration.
	// +kubebuilder:validation:Optional
	TargetIntegrationRef *v2.NamespacedReference `json:"targetIntegrationRef,omitempty" tf:"-"`

	// Selector for a Integration in network to populate targetIntegration.
	// +kubebuilder:validation:Optional
	TargetIntegrationSelector *v2.NamespacedSelector `json:"targetIntegrationSelector,omitempty" tf:"-"`

	// required - Which network to create a peering with
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/network/v1alpha1.Network
	// +kubebuilder:validation:Optional
	TargetNetwork *string `json:"targetNetwork,omitempty" tf:"target_network,omitempty"`

	// Reference to a Network in network to populate targetNetwork.
	// +kubebuilder:validation:Optional
	TargetNetworkRef *v2.NamespacedReference `json:"targetNetworkRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate targetNetwork.
	// +kubebuilder:validation:Optional
	TargetNetworkSelector *v2.NamespacedSelector `json:"targetNetworkSelector,omitempty" tf:"-"`

	// Optional - Which project the target network exists in
	// +kubebuilder:validation:Optional
	TargetProject *string `json:"targetProject,omitempty" tf:"target_project,omitempty"`

	// Optional - Type of network peering
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// PeerSpec defines the desired state of Peer
type PeerSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PeerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PeerInitParameters `json:"initProvider,omitempty"`
}

// PeerStatus defines the observed state of Peer.
type PeerStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PeerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Peer is the Schema for the Peers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,incus}
type Peer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PeerSpec   `json:"spec"`
	Status            PeerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PeerList contains a list of Peers
type PeerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Peer `json:"items"`
}

// Repository type metadata.
var (
	Peer_Kind             = "Peer"
	Peer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Peer_Kind}.String()
	Peer_KindAPIVersion   = Peer_Kind + "." + CRDGroupVersion.String()
	Peer_GroupVersionKind = CRDGroupVersion.WithKind(Peer_Kind)
)

func init() {
	SchemeBuilder.Register(&Peer{}, &PeerList{})
}
