// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ZoneInitParameters struct {

	// Optional - Map of key/value pairs of
	// network zone_config settings.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network zone.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - Name of the network zone.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Optional - Name of the project where the network zone will be created.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`
}

type ZoneObservation struct {

	// Optional - Map of key/value pairs of
	// network zone_config settings.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network zone.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Required - Name of the network zone.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Optional - Name of the project where the network zone will be created.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`
}

type ZoneParameters struct {

	// Optional - Map of key/value pairs of
	// network zone_config settings.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network zone.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - Name of the network zone.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Optional - Name of the project where the network zone will be created.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	// +kubebuilder:validation:Optional
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`
}

// ZoneSpec defines the desired state of Zone
type ZoneSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ZoneParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZoneInitParameters `json:"initProvider,omitempty"`
}

// ZoneStatus defines the observed state of Zone.
type ZoneStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ZoneObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Zone is the Schema for the Zones API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,incus}
type Zone struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ZoneSpec   `json:"spec"`
	Status ZoneStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZoneList contains a list of Zones
type ZoneList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Zone `json:"items"`
}

// Repository type metadata.
var (
	Zone_Kind             = "Zone"
	Zone_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Zone_Kind}.String()
	Zone_KindAPIVersion   = Zone_Kind + "." + CRDGroupVersion.String()
	Zone_GroupVersionKind = CRDGroupVersion.WithKind(Zone_Kind)
)

func init() {
	SchemeBuilder.Register(&Zone{}, &ZoneList{})
}
