// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EntryInitParameters struct {

	// Optional - Entry time to live (TTL).
	// Record entry TTL
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// Required - Entry type. Valid values are DNS record type, e.g. A, AAAA, CNAME, TXT, etc.
	// Record entry type
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Required - Entry value.
	// Record entry value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EntryObservation struct {

	// Optional - Entry time to live (TTL).
	// Record entry TTL
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// Required - Entry type. Valid values are DNS record type, e.g. A, AAAA, CNAME, TXT, etc.
	// Record entry type
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Required - Entry value.
	// Record entry value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EntryParameters struct {

	// Optional - Entry time to live (TTL).
	// Record entry TTL
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// Required - Entry type. Valid values are DNS record type, e.g. A, AAAA, CNAME, TXT, etc.
	// Record entry type
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// Required - Entry value.
	// Record entry value
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type ZoneRecordInitParameters struct {

	// Optional - Map of key/value pairs of
	// network zone_config settings.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network zone.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Optional - Entry in network zone record - see below.
	// Network zone record entry
	Entry []EntryInitParameters `json:"entry,omitempty" tf:"entry,omitempty"`

	// Optional - Name of the project where the network zone record will be created.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Required - Name of the zone to add the entries of this record.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/network/v1alpha1.Zone
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`

	// Reference to a Zone in network to populate zone.
	// +kubebuilder:validation:Optional
	ZoneRef *v2.NamespacedReference `json:"zoneRef,omitempty" tf:"-"`

	// Selector for a Zone in network to populate zone.
	// +kubebuilder:validation:Optional
	ZoneSelector *v2.NamespacedSelector `json:"zoneSelector,omitempty" tf:"-"`
}

type ZoneRecordObservation struct {

	// Optional - Map of key/value pairs of
	// network zone_config settings.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network zone.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Optional - Entry in network zone record - see below.
	// Network zone record entry
	Entry []EntryObservation `json:"entry,omitempty" tf:"entry,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Optional - Name of the project where the network zone record will be created.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Required - Name of the zone to add the entries of this record.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type ZoneRecordParameters struct {

	// Optional - Map of key/value pairs of
	// network zone_config settings.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network zone.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Optional - Entry in network zone record - see below.
	// Network zone record entry
	// +kubebuilder:validation:Optional
	Entry []EntryParameters `json:"entry,omitempty" tf:"entry,omitempty"`

	// Optional - Name of the project where the network zone record will be created.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	// +kubebuilder:validation:Optional
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Required - Name of the zone to add the entries of this record.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/network/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`

	// Reference to a Zone in network to populate zone.
	// +kubebuilder:validation:Optional
	ZoneRef *v2.NamespacedReference `json:"zoneRef,omitempty" tf:"-"`

	// Selector for a Zone in network to populate zone.
	// +kubebuilder:validation:Optional
	ZoneSelector *v2.NamespacedSelector `json:"zoneSelector,omitempty" tf:"-"`
}

// ZoneRecordSpec defines the desired state of ZoneRecord
type ZoneRecordSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ZoneRecordParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZoneRecordInitParameters `json:"initProvider,omitempty"`
}

// ZoneRecordStatus defines the observed state of ZoneRecord.
type ZoneRecordStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ZoneRecordObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ZoneRecord is the Schema for the ZoneRecords API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,incus}
type ZoneRecord struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ZoneRecordSpec   `json:"spec"`
	Status            ZoneRecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZoneRecordList contains a list of ZoneRecords
type ZoneRecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZoneRecord `json:"items"`
}

// Repository type metadata.
var (
	ZoneRecord_Kind             = "ZoneRecord"
	ZoneRecord_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ZoneRecord_Kind}.String()
	ZoneRecord_KindAPIVersion   = ZoneRecord_Kind + "." + CRDGroupVersion.String()
	ZoneRecord_GroupVersionKind = CRDGroupVersion.WithKind(ZoneRecord_Kind)
)

func init() {
	SchemeBuilder.Register(&ZoneRecord{}, &ZoneRecordList{})
}
