// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type NetworkInitParameters struct {

	// Optional - Map of key/value pairs of
	// network config settings. The config should be identical for all resources referencing the same clustered network, only members keys may differ.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network. description is mutual exclusive with target. The description can only be set on cluster level (with target not set) or on non-clustered setups.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - Name of the network. This is usually the device the
	// network will appear as to instances.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Optional - Name of the project where the network will be created.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/cluster/project/v1alpha1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.Reference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.Selector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - Specify a target node in a cluster.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// Optional - The type of network to create. Can be one of: bridge,
	// macvlan, sriov, ovn, or physical. If no type is specified, a bridge network
	// is created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type NetworkObservation struct {

	// Optional - Map of key/value pairs of
	// network config settings. The config should be identical for all resources referencing the same clustered network, only members keys may differ.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network. description is mutual exclusive with target. The description can only be set on cluster level (with target not set) or on non-clustered setups.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether or not the network is managed.
	Managed *bool `json:"managed,omitempty" tf:"managed,omitempty"`

	// Required - Name of the network. This is usually the device the
	// network will appear as to instances.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Optional - Name of the project where the network will be created.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - Specify a target node in a cluster.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// Optional - The type of network to create. Can be one of: bridge,
	// macvlan, sriov, ovn, or physical. If no type is specified, a bridge network
	// is created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type NetworkParameters struct {

	// Optional - Map of key/value pairs of
	// network config settings. The config should be identical for all resources referencing the same clustered network, only members keys may differ.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the network. description is mutual exclusive with target. The description can only be set on cluster level (with target not set) or on non-clustered setups.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - Name of the network. This is usually the device the
	// network will appear as to instances.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Optional - Name of the project where the network will be created.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/cluster/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.Reference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.Selector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	// +kubebuilder:validation:Optional
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - Specify a target node in a cluster.
	// +kubebuilder:validation:Optional
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// Optional - The type of network to create. Can be one of: bridge,
	// macvlan, sriov, ovn, or physical. If no type is specified, a bridge network
	// is created.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// NetworkSpec defines the desired state of Network
type NetworkSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   NetworkParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkInitParameters `json:"initProvider,omitempty"`
}

// NetworkStatus defines the observed state of Network.
type NetworkStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               NetworkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Network is the Schema for the Networks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incus}
type Network struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   NetworkSpec   `json:"spec"`
	Status NetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkList contains a list of Networks
type NetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Network `json:"items"`
}

// Repository type metadata.
var (
	Network_Kind             = "Network"
	Network_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Network_Kind}.String()
	Network_KindAPIVersion   = Network_Kind + "." + CRDGroupVersion.String()
	Network_GroupVersionKind = CRDGroupVersion.WithKind(Network_Kind)
)

func init() {
	SchemeBuilder.Register(&Network{}, &NetworkList{})
}
