apiVersion: image.incus.m.crossplane.io/v1alpha1
kind: Image
metadata:
  annotations:
    meta.upbound.io/example-id: image/v1alpha1/image
  labels:
    testing.upbound.io/example-name: alpine
  name: alpine
  namespace: crossplane-system
spec:
  forProvider:
    sourceImage:
      name: alpine/edge
      remote: images

---

apiVersion: instance.incus.m.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: image/v1alpha1/image
  labels:
    testing.upbound.io/example-name: test1
  name: test1
  namespace: crossplane-system
spec:
  forProvider:
    ephemeral: false
    imageSelector:
      matchLabels:
        testing.upbound.io/example-name: alpine
