apiVersion: storage.incus.crossplane.io/v1alpha1
kind: BucketKey
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/bucketkey
  labels:
    testing.upbound.io/example-name: key1
  name: key1
spec:
  forProvider:
    poolSelector:
      matchLabels:
        testing.upbound.io/example-name: bucket1
    storageBucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucket1

---

apiVersion: storage.incus.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/bucketkey
  labels:
    testing.upbound.io/example-name: bucket1
  name: bucket1
spec:
  forProvider:
    poolSelector:
      matchLabels:
        testing.upbound.io/example-name: pool1

---

apiVersion: storage.incus.crossplane.io/v1alpha1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/bucketkey
  labels:
    testing.upbound.io/example-name: pool1
  name: pool1
spec:
  forProvider:
    driver: zfs
    name: mypool
