// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type BucketInitParameters struct {

	// Optional - Map of key/value pairs of
	// storage bucket config settings.
	// Config settings vary depending on the Storage Pool used.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the storage bucket.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - Name of storage pool to host the storage bucket.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/storage/v1alpha1.Pool
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// Reference to a Pool in storage to populate pool.
	// +kubebuilder:validation:Optional
	PoolRef *v2.NamespacedReference `json:"poolRef,omitempty" tf:"-"`

	// Selector for a Pool in storage to populate pool.
	// +kubebuilder:validation:Optional
	PoolSelector *v2.NamespacedSelector `json:"poolSelector,omitempty" tf:"-"`

	// Optional - Name of the project where the storage bucket will be stored.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - Path to a backup file from which the bucket will be created.
	SourceFile *string `json:"sourceFile,omitempty" tf:"source_file,omitempty"`

	// Optional - Specify a target node in a cluster.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`
}

type BucketObservation struct {

	// Optional - Map of key/value pairs of
	// storage bucket config settings.
	// Config settings vary depending on the Storage Pool used.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the storage bucket.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the node where storage bucket was created. It could be useful with Incus in cluster mode.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Required - Name of storage pool to host the storage bucket.
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// Optional - Name of the project where the storage bucket will be stored.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - Path to a backup file from which the bucket will be created.
	SourceFile *string `json:"sourceFile,omitempty" tf:"source_file,omitempty"`

	// Optional - Specify a target node in a cluster.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`
}

type BucketParameters struct {

	// Optional - Map of key/value pairs of
	// storage bucket config settings.
	// Config settings vary depending on the Storage Pool used.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the storage bucket.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Required - Name of storage pool to host the storage bucket.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/storage/v1alpha1.Pool
	// +kubebuilder:validation:Optional
	Pool *string `json:"pool,omitempty" tf:"pool,omitempty"`

	// Reference to a Pool in storage to populate pool.
	// +kubebuilder:validation:Optional
	PoolRef *v2.NamespacedReference `json:"poolRef,omitempty" tf:"-"`

	// Selector for a Pool in storage to populate pool.
	// +kubebuilder:validation:Optional
	PoolSelector *v2.NamespacedSelector `json:"poolSelector,omitempty" tf:"-"`

	// Optional - Name of the project where the storage bucket will be stored.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	// +kubebuilder:validation:Optional
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - Path to a backup file from which the bucket will be created.
	// +kubebuilder:validation:Optional
	SourceFile *string `json:"sourceFile,omitempty" tf:"source_file,omitempty"`

	// Optional - Specify a target node in a cluster.
	// +kubebuilder:validation:Optional
	Target *string `json:"target,omitempty" tf:"target,omitempty"`
}

// BucketSpec defines the desired state of Bucket
type BucketSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BucketParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BucketInitParameters `json:"initProvider,omitempty"`
}

// BucketStatus defines the observed state of Bucket.
type BucketStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               BucketObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Bucket is the Schema for the Buckets API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,incus}
type Bucket struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BucketSpec   `json:"spec"`
	Status            BucketStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BucketList contains a list of Buckets
type BucketList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Bucket `json:"items"`
}

// Repository type metadata.
var (
	Bucket_Kind             = "Bucket"
	Bucket_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Bucket_Kind}.String()
	Bucket_KindAPIVersion   = Bucket_Kind + "." + CRDGroupVersion.String()
	Bucket_GroupVersionKind = CRDGroupVersion.WithKind(Bucket_Kind)
)

func init() {
	SchemeBuilder.Register(&Bucket{}, &BucketList{})
}
