// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DeviceInitParameters struct {

	// Required - Name of the device.
	// Device name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Required - Map of key/value pairs of
	// device properties.
	// Device properties
	// +mapType=granular
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// Required - Type of the device Must be one of none, disk, nic,
	// unix-char, unix-block, usb, gpu, infiniband, proxy, unix-hotplug, tpm, pci.
	// Device type
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DeviceObservation struct {

	// Required - Name of the device.
	// Device name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Required - Map of key/value pairs of
	// device properties.
	// Device properties
	// +mapType=granular
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// Required - Type of the device Must be one of none, disk, nic,
	// unix-char, unix-block, usb, gpu, infiniband, proxy, unix-hotplug, tpm, pci.
	// Device type
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DeviceParameters struct {

	// Required - Name of the device.
	// Device name
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Required - Map of key/value pairs of
	// device properties.
	// Device properties
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Properties map[string]*string `json:"properties" tf:"properties,omitempty"`

	// Required - Type of the device Must be one of none, disk, nic,
	// unix-char, unix-block, usb, gpu, infiniband, proxy, unix-hotplug, tpm, pci.
	// Device type
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type ExecInitParameters struct {

	// Required - Command to execute as a list of strings where the first
	// element is the executable and the rest are arguments.
	Command []*string `json:"command,omitempty" tf:"command,omitempty"`

	// Optional - Map of environment variables to set for the command.
	// +mapType=granular
	Environment map[string]*string `json:"environment,omitempty" tf:"environment,omitempty"`

	// Optional - The GID to run the command as.
	GID *float64 `json:"gid,omitempty" tf:"gid,omitempty"`

	// Optional - Timeout for the command, e.g. 30s or 5m.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Optional - When to run the command. Supported values are on_change,
	// and once. Defaults to on_change.
	Trigger *string `json:"trigger,omitempty" tf:"trigger,omitempty"`

	// Optional - The UID to run the command as.
	UID *float64 `json:"uid,omitempty" tf:"uid,omitempty"`

	// Optional - Working directory for the command.
	WorkingDir *string `json:"workingDir,omitempty" tf:"working_dir,omitempty"`
}

type ExecObservation struct {

	// Required - Command to execute as a list of strings where the first
	// element is the executable and the rest are arguments.
	Command []*string `json:"command,omitempty" tf:"command,omitempty"`

	// Optional - Map of environment variables to set for the command.
	// +mapType=granular
	Environment map[string]*string `json:"environment,omitempty" tf:"environment,omitempty"`

	// Optional - The GID to run the command as.
	GID *float64 `json:"gid,omitempty" tf:"gid,omitempty"`

	// Optional - Timeout for the command, e.g. 30s or 5m.
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Optional - When to run the command. Supported values are on_change,
	// and once. Defaults to on_change.
	Trigger *string `json:"trigger,omitempty" tf:"trigger,omitempty"`

	// Optional - The UID to run the command as.
	UID *float64 `json:"uid,omitempty" tf:"uid,omitempty"`

	// Optional - Working directory for the command.
	WorkingDir *string `json:"workingDir,omitempty" tf:"working_dir,omitempty"`
}

type ExecParameters struct {

	// Required - Command to execute as a list of strings where the first
	// element is the executable and the rest are arguments.
	// +kubebuilder:validation:Optional
	Command []*string `json:"command" tf:"command,omitempty"`

	// Optional - Map of environment variables to set for the command.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Environment map[string]*string `json:"environment,omitempty" tf:"environment,omitempty"`

	// Optional - The GID to run the command as.
	// +kubebuilder:validation:Optional
	GID *float64 `json:"gid,omitempty" tf:"gid,omitempty"`

	// Optional - Timeout for the command, e.g. 30s or 5m.
	// +kubebuilder:validation:Optional
	Timeout *string `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Optional - When to run the command. Supported values are on_change,
	// and once. Defaults to on_change.
	// +kubebuilder:validation:Optional
	Trigger *string `json:"trigger,omitempty" tf:"trigger,omitempty"`

	// Optional - The UID to run the command as.
	// +kubebuilder:validation:Optional
	UID *float64 `json:"uid,omitempty" tf:"uid,omitempty"`

	// Optional - Working directory for the command.
	// +kubebuilder:validation:Optional
	WorkingDir *string `json:"workingDir,omitempty" tf:"working_dir,omitempty"`
}

type FileInitParameters struct {

	// Required unless source_path is used* - The contents of the file.
	// Use the file() function to read in the content of a file from disk.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// Optional - Whether to create the directories leading
	// to the target if they do not exist.
	CreateDirectories *bool `json:"createDirectories,omitempty" tf:"create_directories,omitempty"`

	DirectoryMode *string `json:"directoryMode,omitempty" tf:"directory_mode,omitempty"`

	// Optional - The GID of the file. Must be an unquoted integer.
	GID *float64 `json:"gid,omitempty" tf:"gid,omitempty"`

	// Optional - The octal permissions of the file, must be quoted. Defaults to 0755.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// Required unless content is used* - The source path to a file to
	// copy to the instance.
	SourcePath *string `json:"sourcePath,omitempty" tf:"source_path,omitempty"`

	// Required - The absolute path of the file on the instance,
	// including the filename.
	TargetPath *string `json:"targetPath,omitempty" tf:"target_path,omitempty"`

	// Optional - The UID of the file. Must be an unquoted integer.
	UID *float64 `json:"uid,omitempty" tf:"uid,omitempty"`
}

type FileObservation struct {
	Append *bool `json:"append,omitempty" tf:"append,omitempty"`

	// Required unless source_path is used* - The contents of the file.
	// Use the file() function to read in the content of a file from disk.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// Optional - Whether to create the directories leading
	// to the target if they do not exist.
	CreateDirectories *bool `json:"createDirectories,omitempty" tf:"create_directories,omitempty"`

	DirectoryMode *string `json:"directoryMode,omitempty" tf:"directory_mode,omitempty"`

	// Optional - The GID of the file. Must be an unquoted integer.
	GID *float64 `json:"gid,omitempty" tf:"gid,omitempty"`

	// Optional - The octal permissions of the file, must be quoted. Defaults to 0755.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// Required unless content is used* - The source path to a file to
	// copy to the instance.
	SourcePath *string `json:"sourcePath,omitempty" tf:"source_path,omitempty"`

	// Required - The absolute path of the file on the instance,
	// including the filename.
	TargetPath *string `json:"targetPath,omitempty" tf:"target_path,omitempty"`

	// Optional - The UID of the file. Must be an unquoted integer.
	UID *float64 `json:"uid,omitempty" tf:"uid,omitempty"`
}

type FileParameters struct {

	// Required unless source_path is used* - The contents of the file.
	// Use the file() function to read in the content of a file from disk.
	// +kubebuilder:validation:Optional
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// Optional - Whether to create the directories leading
	// to the target if they do not exist.
	// +kubebuilder:validation:Optional
	CreateDirectories *bool `json:"createDirectories,omitempty" tf:"create_directories,omitempty"`

	// +kubebuilder:validation:Optional
	DirectoryMode *string `json:"directoryMode,omitempty" tf:"directory_mode,omitempty"`

	// Optional - The GID of the file. Must be an unquoted integer.
	// +kubebuilder:validation:Optional
	GID *float64 `json:"gid,omitempty" tf:"gid,omitempty"`

	// Optional - The octal permissions of the file, must be quoted. Defaults to 0755.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// Required unless content is used* - The source path to a file to
	// copy to the instance.
	// +kubebuilder:validation:Optional
	SourcePath *string `json:"sourcePath,omitempty" tf:"source_path,omitempty"`

	// Required - The absolute path of the file on the instance,
	// including the filename.
	// +kubebuilder:validation:Optional
	TargetPath *string `json:"targetPath" tf:"target_path,omitempty"`

	// Optional - The UID of the file. Must be an unquoted integer.
	// +kubebuilder:validation:Optional
	UID *float64 `json:"uid,omitempty" tf:"uid,omitempty"`
}

type IPAddressesInitParameters struct {
}

type IPAddressesObservation struct {

	// IP address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// IP family (inet, inet6)
	Family *string `json:"family,omitempty" tf:"family,omitempty"`

	// Scope (local, global, link)
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type IPAddressesParameters struct {
}

type InstanceInitParameters struct {

	// Optional - The instance architecture (e.g. x86_64, aarch64). See Architectures for all possible values.
	Architecture *string `json:"architecture,omitempty" tf:"architecture,omitempty"`

	// Optional - Map of key/value pairs of
	// instance config settings.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the instance.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Optional - Device definition. See reference below.
	// Profile device
	Device []DeviceInitParameters `json:"device,omitempty" tf:"device,omitempty"`

	// Optional - Boolean indicating if this instance is ephemeral. Defaults to false.
	Ephemeral *bool `json:"ephemeral,omitempty" tf:"ephemeral,omitempty"`

	// Optional - Map of exec commands to run on the instance. See reference below.
	Exec map[string]ExecInitParameters `json:"exec,omitempty" tf:"exec,omitempty"`

	// Optional - File to upload to the instance. See reference below.
	// Upload file to instance
	File []FileInitParameters `json:"file,omitempty" tf:"file,omitempty"`

	// Optional - Base image from which the instance will be created. Must
	// specify an image accessible from the provider remote.
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// Optional - List of Incus config profiles to apply to the new
	// instance. Profile default will be applied if profiles are not set (are null).
	// However, if an empty array ([]) is set as a value, no profiles will be applied.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/cluster/profile/v1alpha1.Profile
	Profiles []*string `json:"profiles,omitempty" tf:"profiles,omitempty"`

	// References to Profile in profile to populate profiles.
	// +kubebuilder:validation:Optional
	ProfilesRefs []v2.Reference `json:"profilesRefs,omitempty" tf:"-"`

	// Selector for a list of Profile in profile to populate profiles.
	// +kubebuilder:validation:Optional
	ProfilesSelector *v2.Selector `json:"profilesSelector,omitempty" tf:"-"`

	// Optional - Name of the project where the instance will be spawned.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/cluster/project/v1alpha1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.Reference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.Selector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - Boolean indicating whether the instance should be started (running). Defaults to true.
	Running *bool `json:"running,omitempty" tf:"running,omitempty"`

	// Optional - The souce backup file from which the instance should be restored. For handling of storage pool, see examples.
	SourceFile *string `json:"sourceFile,omitempty" tf:"source_file,omitempty"`

	// Optional - The source instance from which the instance will be created. See reference below.
	SourceInstance *SourceInstanceInitParameters `json:"sourceInstance,omitempty" tf:"source_instance,omitempty"`

	// Optional - Specify a target node in a cluster.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// Optional - Instance type. Can be container, or virtual-machine. Defaults to container.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Optional - WaitFor definition. See reference below.
	// If running is set to false or instance is already running (on update), this value has no effect.
	// Wait for instance to be ready
	WaitFor []WaitForInitParameters `json:"waitFor,omitempty" tf:"wait_for,omitempty"`
}

type InstanceObservation struct {

	// Optional - The instance architecture (e.g. x86_64, aarch64). See Architectures for all possible values.
	Architecture *string `json:"architecture,omitempty" tf:"architecture,omitempty"`

	// Optional - Map of key/value pairs of
	// instance config settings.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the instance.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Optional - Device definition. See reference below.
	// Profile device
	Device []DeviceObservation `json:"device,omitempty" tf:"device,omitempty"`

	// Optional - Boolean indicating if this instance is ephemeral. Defaults to false.
	Ephemeral *bool `json:"ephemeral,omitempty" tf:"ephemeral,omitempty"`

	// Optional - Map of exec commands to run on the instance. See reference below.
	Exec map[string]ExecObservation `json:"exec,omitempty" tf:"exec,omitempty"`

	// Optional - File to upload to the instance. See reference below.
	// Upload file to instance
	File []FileObservation `json:"file,omitempty" tf:"file,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The IPv4 Address of the instance. See Instance Network
	// Access for more details.
	IPv4Address *string `json:"ipv4Address,omitempty" tf:"ipv4_address,omitempty"`

	// The IPv6 Address of the instance. See Instance Network
	// Access for more details.
	IPv6Address *string `json:"ipv6Address,omitempty" tf:"ipv6_address,omitempty"`

	// Optional - Base image from which the instance will be created. Must
	// specify an image accessible from the provider remote.
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// Map of all instance network interfaces (excluding loopback device). The map key represents the name of the network device (from Incus configuration).
	Interfaces map[string]InterfacesObservation `json:"interfaces,omitempty" tf:"interfaces,omitempty"`

	// The MAC address of the detected NIC. See Instance Network
	// Access for more details.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// Optional - List of Incus config profiles to apply to the new
	// instance. Profile default will be applied if profiles are not set (are null).
	// However, if an empty array ([]) is set as a value, no profiles will be applied.
	Profiles []*string `json:"profiles,omitempty" tf:"profiles,omitempty"`

	// Optional - Name of the project where the instance will be spawned.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - Boolean indicating whether the instance should be started (running). Defaults to true.
	Running *bool `json:"running,omitempty" tf:"running,omitempty"`

	// Optional - The souce backup file from which the instance should be restored. For handling of storage pool, see examples.
	SourceFile *string `json:"sourceFile,omitempty" tf:"source_file,omitempty"`

	// Optional - The source instance from which the instance will be created. See reference below.
	SourceInstance *SourceInstanceObservation `json:"sourceInstance,omitempty" tf:"source_instance,omitempty"`

	// The status of the instance.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Optional - Specify a target node in a cluster.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// Optional - Instance type. Can be container, or virtual-machine. Defaults to container.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Optional - WaitFor definition. See reference below.
	// If running is set to false or instance is already running (on update), this value has no effect.
	// Wait for instance to be ready
	WaitFor []WaitForObservation `json:"waitFor,omitempty" tf:"wait_for,omitempty"`
}

type InstanceParameters struct {

	// Optional - The instance architecture (e.g. x86_64, aarch64). See Architectures for all possible values.
	// +kubebuilder:validation:Optional
	Architecture *string `json:"architecture,omitempty" tf:"architecture,omitempty"`

	// Optional - Map of key/value pairs of
	// instance config settings.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Optional - Description of the instance.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Optional - Device definition. See reference below.
	// Profile device
	// +kubebuilder:validation:Optional
	Device []DeviceParameters `json:"device,omitempty" tf:"device,omitempty"`

	// Optional - Boolean indicating if this instance is ephemeral. Defaults to false.
	// +kubebuilder:validation:Optional
	Ephemeral *bool `json:"ephemeral,omitempty" tf:"ephemeral,omitempty"`

	// Optional - Map of exec commands to run on the instance. See reference below.
	// +kubebuilder:validation:Optional
	Exec map[string]ExecParameters `json:"exec,omitempty" tf:"exec,omitempty"`

	// Optional - File to upload to the instance. See reference below.
	// Upload file to instance
	// +kubebuilder:validation:Optional
	File []FileParameters `json:"file,omitempty" tf:"file,omitempty"`

	// Optional - Base image from which the instance will be created. Must
	// specify an image accessible from the provider remote.
	// +kubebuilder:validation:Optional
	Image *string `json:"image,omitempty" tf:"image,omitempty"`

	// Optional - List of Incus config profiles to apply to the new
	// instance. Profile default will be applied if profiles are not set (are null).
	// However, if an empty array ([]) is set as a value, no profiles will be applied.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/cluster/profile/v1alpha1.Profile
	// +kubebuilder:validation:Optional
	Profiles []*string `json:"profiles,omitempty" tf:"profiles,omitempty"`

	// References to Profile in profile to populate profiles.
	// +kubebuilder:validation:Optional
	ProfilesRefs []v2.Reference `json:"profilesRefs,omitempty" tf:"-"`

	// Selector for a list of Profile in profile to populate profiles.
	// +kubebuilder:validation:Optional
	ProfilesSelector *v2.Selector `json:"profilesSelector,omitempty" tf:"-"`

	// Optional - Name of the project where the instance will be spawned.
	// +crossplane:generate:reference:type=github.com/l-nmch/provider-incus/apis/cluster/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.Reference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.Selector `json:"projectSelector,omitempty" tf:"-"`

	// Optional - The remote in which the resource will be created. If
	// not provided, the provider's default remote will be used.
	// +kubebuilder:validation:Optional
	Remote *string `json:"remote,omitempty" tf:"remote,omitempty"`

	// Optional - Boolean indicating whether the instance should be started (running). Defaults to true.
	// +kubebuilder:validation:Optional
	Running *bool `json:"running,omitempty" tf:"running,omitempty"`

	// Optional - The souce backup file from which the instance should be restored. For handling of storage pool, see examples.
	// +kubebuilder:validation:Optional
	SourceFile *string `json:"sourceFile,omitempty" tf:"source_file,omitempty"`

	// Optional - The source instance from which the instance will be created. See reference below.
	// +kubebuilder:validation:Optional
	SourceInstance *SourceInstanceParameters `json:"sourceInstance,omitempty" tf:"source_instance,omitempty"`

	// Optional - Specify a target node in a cluster.
	// +kubebuilder:validation:Optional
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// Optional - Instance type. Can be container, or virtual-machine. Defaults to container.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Optional - WaitFor definition. See reference below.
	// If running is set to false or instance is already running (on update), this value has no effect.
	// Wait for instance to be ready
	// +kubebuilder:validation:Optional
	WaitFor []WaitForParameters `json:"waitFor,omitempty" tf:"wait_for,omitempty"`
}

type InterfacesInitParameters struct {
}

type InterfacesObservation struct {
	IPAddresses []IPAddressesObservation `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// Required - Name of the source instance.
	// Name of the network interface within an instance
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// State of the network interface (up, down)
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Required - Type for what should be waited for. Can be agent, cloud-init, delay, ipv4, ipv6 or ready.
	// Type of the network interface (link, local, global)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type InterfacesParameters struct {
}

type SourceInstanceInitParameters struct {

	// Required - Name of the source instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Required - Name of the project in which the source instance exists.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Optional - Name of the snapshot of the source instance
	Snapshot *string `json:"snapshot,omitempty" tf:"snapshot,omitempty"`
}

type SourceInstanceObservation struct {

	// Required - Name of the source instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Required - Name of the project in which the source instance exists.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Optional - Name of the snapshot of the source instance
	Snapshot *string `json:"snapshot,omitempty" tf:"snapshot,omitempty"`
}

type SourceInstanceParameters struct {

	// Required - Name of the source instance.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Required - Name of the project in which the source instance exists.
	// +kubebuilder:validation:Optional
	Project *string `json:"project" tf:"project,omitempty"`

	// Optional - Name of the snapshot of the source instance
	// +kubebuilder:validation:Optional
	Snapshot *string `json:"snapshot,omitempty" tf:"snapshot,omitempty"`
}

type WaitForInitParameters struct {

	// Optional - Delay time that should be waited for when type is delay, e.g. 30s.
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	// Optional - Network interface that should be waited for when type is ipv4 or ipv6.
	Nic *string `json:"nic,omitempty" tf:"nic,omitempty"`

	// Required - Type for what should be waited for. Can be agent, cloud-init, delay, ipv4, ipv6 or ready.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type WaitForObservation struct {

	// Optional - Delay time that should be waited for when type is delay, e.g. 30s.
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	// Optional - Network interface that should be waited for when type is ipv4 or ipv6.
	Nic *string `json:"nic,omitempty" tf:"nic,omitempty"`

	// Required - Type for what should be waited for. Can be agent, cloud-init, delay, ipv4, ipv6 or ready.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type WaitForParameters struct {

	// Optional - Delay time that should be waited for when type is delay, e.g. 30s.
	// +kubebuilder:validation:Optional
	Delay *string `json:"delay,omitempty" tf:"delay,omitempty"`

	// Optional - Network interface that should be waited for when type is ipv4 or ipv6.
	// +kubebuilder:validation:Optional
	Nic *string `json:"nic,omitempty" tf:"nic,omitempty"`

	// Required - Type for what should be waited for. Can be agent, cloud-init, delay, ipv4, ipv6 or ready.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

// InstanceSpec defines the desired state of Instance
type InstanceSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   InstanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceInitParameters `json:"initProvider,omitempty"`
}

// InstanceStatus defines the observed state of Instance.
type InstanceStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               InstanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Instance is the Schema for the Instances API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incus}
type Instance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              InstanceSpec   `json:"spec"`
	Status            InstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceList contains a list of Instances
type InstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Instance `json:"items"`
}

// Repository type metadata.
var (
	Instance_Kind             = "Instance"
	Instance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Instance_Kind}.String()
	Instance_KindAPIVersion   = Instance_Kind + "." + CRDGroupVersion.String()
	Instance_GroupVersionKind = CRDGroupVersion.WithKind(Instance_Kind)
)

func init() {
	SchemeBuilder.Register(&Instance{}, &InstanceList{})
}
